server.port: 8081
management.port: 9981

spring:
  application:
    name: longjian-datathrough-app
  cloud:
    consul:
      enabled: true
      host: 192.168.37.218
      port: 8500
      discovery:
        register: true
        healthCheckInterval: 5s
        fail-fast: false
    sleuth:
      enabled: true

management:
  security:
    enabled: false

# gaia gfs 配置

longfor:
  web:
    feign:
      clients:
        murphy:
          login-murphy-one:
            url: http://192.168.37.71:51004/web/
        config:
          login-murphy-one:
            connectTimeout: 5000 # default 10 * 1000
            readTimeout: 5000 # default 60 * 1000

  data:
    pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
    mybatis:
      typeAliasesPackage: com.longfor.longjian.basic.dao
      mapperLocations:
      - classpath:com/longfor/longjian/basic/dao/*.xml
    mapper:
      notEmpty: true
    #多数据源配置
    database:
      primary: custom02
      connection:
        master:
          #默认数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:siberia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          druid:
            filters: stat
            max-active: 20
            initial-size: 1
            max-wait: 30000
            min-idle: 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            max-open-prepared-statements: -1
            remove-abandoned: true
            remove-abandoned-timeout-millis: 500000
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/download/*,/wj/*,/assets/*'
        custom01:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.36.95:3306/bs_adapter_longhu_sync?useUnicode=true&characterEncoding=UTF8
          username: zhijian
          password: JM4tLp9u6pPANLhT
          hikari:
            #控制从池返回的连接的默认自动提交行为。默认值：true
            auto-commit: true
            #客户端等待连接的最大毫秒数。如果在没有可用连接的情况下超过此时间，则会抛出SQLException。默认值：30000
            connection-timeout: 10000
            #此属性控制允许连接在池中闲置的最长时间。此设置仅适用于minimumIdle定义为小于maximumPoolSize。默认值：600000（10分钟）
            idle-timeout: 600000
            #此属性控制池中连接的最大生存期。默认值：1800000（30分钟）
            max-lifetime: 1800000
            #该属性控制HikariCP尝试在池中维护的最小空闲连接数。默认值：与maximumPoolSize相同
            minimum-idle: 10
            #此属性控制池允许达到的最大大小，包括空闲和正在使用的连接。默认值：10
            maximum-pool-size: 10
        custom02:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.36.95:3306/zhijian2_apisvr?useUnicode=true&characterEncoding=UTF8
          username: zhijian
          password: JM4tLp9u6pPANLhT
    redis:
      namespace: longjian:datathrough:app
      connection:
        dataThroughRedis:
          database: 10
          timeout: 2000
          host: 192.168.36.93
          port: 6379
          pool:
            minIdle: 50
            maxActive: 50


master:
  msg:
    mdmSuccess: http://192.168.37.181:50000/RESTAdapter/PO/V1.0/MasterData/PPSReceiveOK
    mdmError: http://192.168.37.181:50000/RESTAdapter/PO/V1.0/MasterData/PPSErrorLog

murphy:
  system:
    tenantTriggerId: 49186334960717832
    hearder-token-key: x-authentication-token
    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwMDM3ODI0NTY4OTEzOTIwIiwic3QiOiIxIiwibG4iOiJsb25namlhbjExMTYiLCJwaSI6IjE2MDAzNzgyNDU2ODkxMzkyMCIsInJuIjoi6b6Z5bu657O757ufIn0.eRexfAemDGFi2_gBLBrq4qHrLHdJWU5F8a9DbWYlrCM
  login:
    interfaceOne: http://192.168.37.71:51004/web/api/login/baseMurphy
    interfaceTwo: http://192.168.37.71:51004/web/api/login/baseMurphyAdditionalCheck
    interfaceThree: http://192.168.37.71:51004/web/api/login/baseMurphySelectTenant
  encrypt:
    modulus: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbyPqrjU6XSMm+IPdek0dNt56T4D3nOmD1v3G/1ardRaS1b6hon2ZOicfldM+jANTUHrJ4eEOQ704TGgLqWbEmsVHASnCghHiLuk+UuxEgZNk4i+q9i2x+y8yvxx1qN42ehl4bO3gDla5wOSZF/MZCxK3P1WnwBFjlhwFhyZyi0QIDAQAB

longjian:
  domain: testlongjianapp.longhu.net









