server.port: 8080
management.port: 9981

spring:
  application:
    name: longjian-datathrough-app
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        register: true
        healthCheckInterval: 5s
        fail-fast: false
        preferIpAddress: true
    sleuth:
      enabled: true

management:
  security:
    enabled: false

# gaia gfs 配置

longfor:
  web:
    feign:
      clients:
        galactic:
          push-stage:
            url: http://10.238.63.150:51001/receive/ #文档接收分期接口
        config:
          login-murphy-one:
            connectTimeout: 5000 # default 10 * 1000
            readTimeout: 5000 # default 60 * 1000
    logging:
      kafka:
        enabled: true
        broker: kafka01.paas.longhu.net:9092,kafka02.paas.longhu.net:9092,kafka03.paas.longhu.net:9092
        env: test

  data:
    pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
    mybatis:
      typeAliasesPackage: com.longfor.longjian.datathrough.dao
      mapperLocations:
      - classpath:com/longfor/longjian/datathrough/dao/*.xml
    mapper:
      notEmpty: true
    #多数据源配置
    database:
      primary: master
      connection:
        master:
          #默认数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.36.95:3306/zhijian2_apisvr?useUnicode=true&characterEncoding=UTF8
          username: zhijian
          password: JM4tLp9u6pPANLhT
          druid:
            filters: stat
            max-active: 20   #最大连接池数量
            initial-size: 1  #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
            max-wait: 30000  #获取连接等待超时的时间
            min-idle: 1
            time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            min-evictable-idle-time-millis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            max-open-prepared-statements: -1
            remove-abandoned: true
            remove-abandoned-timeout-millis: 500000
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/download/*,/wj/*,/assets/*'
        custom01: #custom01 并没有指定连接池, 系统会默认使用 druid(前提是 maven引入了 druid依赖, 如果没有引入, 则不使用连接池).
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.36.95:3306/bs_adapter_longhu_sync?useUnicode=true&characterEncoding=UTF8
          username: zhijian
          password: JM4tLp9u6pPANLhT
    redis:
      namespace: longjian:datathrough:app
      connection:
        dataThroughRedis:
          database: 10
          timeout: 2000
          host: 192.168.36.93
          port: 6379
          pool:
            minIdle: 50
            maxActive: 50


master:
  msg:
    mdmSuccess: http://192.168.37.181:50000/RESTAdapter/PO/V1.0/MasterData/PPSReceiveOK
    mdmError: http://192.168.37.181:50000/RESTAdapter/PO/V1.0/MasterData/PPSErrorLog
  whitelist:
    enabled: false
    list: 192.168.32.23
